- name: Hello World Sample
  hosts: all
  tasks:
    - debug:
              var: hostvars[inventory_hostname]

    # - name: Call API
    #   include_tasks: import_task_test.yml
    #   loop: 
    #     - test
    #     - test2